version: "3.7"

services:
  db:
    image: mysql:8.0.17
    container_name: database
    volumes:
      - database-volume:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: pokemonbook
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo1234
  adminer:
    image: adminer
    ports:
      - 9012:8080

volumes:
  database-volume:
